// <auto-generated />
using System;
using Library_Test.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library_Test.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20200402093028_DB_Context.LibraryContextSeed_1")]
    partial class DB_ContextLibraryContextSeed_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Library_Test.Entities.Books", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("CoverPrice")
                        .HasColumnType("money");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PublishYear")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("BookId");

                    b.ToTable("Books","dbo");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("73a2f969-eda1-44d6-8512-aa49fdc3e633"),
                            AvailabilityStatus = "check-in",
                            CoverPrice = 1800.00m,
                            Isbn = "1234-PPL-HS",
                            PublishYear = "2020",
                            Title = "Being a great Staff of Health Station"
                        },
                        new
                        {
                            BookId = new Guid("54e6c636-55f6-4176-97ca-60cb32e8ed8e"),
                            AvailabilityStatus = "check-Out",
                            CoverPrice = 1800.00m,
                            Isbn = "13454-PPL-HS",
                            PublishYear = "2020",
                            Title = "INterview 101"
                        });
                });

            modelBuilder.Entity("Library_Test.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BookId");

                    b.Property<DateTime>("DateOfCheckout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ExpectedDateOfReturn")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NationalIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("Users","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
